# Generated by Django 4.2 on 2025-05-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculoplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
