# Generated by Django 4.2 on 2025-05-15 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0004_rename_convenio_sucursal_id_convenio_and_more'),
        ('Requests', '0002_plan_is_active_solicitud_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='central_servicios',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='turno',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_convenio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Access.convenio'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Access.sucursal'),
        ),
    ]
