# Generated by Django 4.2 on 2025-05-15 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0004_rename_convenio_sucursal_id_convenio_and_more'),
        ('Requests', '0003_remove_solicitud_central_servicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id_convenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Access.convenio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Access.sucursal'),
        ),
    ]
