# Generated by Django 4.2 on 2025-05-15 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0004_alter_solicitud_id_convenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
