# Generated by Django 4.2 on 2025-05-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0003_categoriaformularios_formulario_id_categoria'),
        ('Requests', '0005_alter_solicitud_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cuestionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forms.categoriaformularios'),
        ),
        migrations.AddField(
            model_name='plan',
            name='id_tipo_vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Requests.tipovehiculo'),
        ),
        migrations.AddField(
            model_name='plan',
            name='lista_adicionales',
            field=models.ManyToManyField(to='Forms.formulario'),
        ),
    ]
