# Generated by Django 4.2 on 2025-05-21 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0006_plan_cuestionario_plan_id_tipo_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 5, 21)),
        ),
    ]
