# Generated by Django 4.2 on 2025-05-21 16:26

import apps.Requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0007_alter_solicitud_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(default=apps.Requests.models.Solicitud),
        ),
    ]
