# Generated by Django 4.2 on 2025-05-21 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0008_alter_solicitud_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
