# Generated by Django 4.2 on 2025-06-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0009_alter_solicitud_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('AC', 'Activo'), ('CAL', 'Cancelado'), ('PRO', 'En Progreso'), ('FIN', 'Finalizado')], default='AC', max_length=3),
        ),
    ]
