# Generated by Django 4.2 on 2025-06-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0010_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
