# Generated by Django 4.2 on 2025-09-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0011_solicitud_fecha_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculoplan',
            name='id_plan',
        ),
        migrations.RemoveField(
            model_name='vehiculoplan',
            name='id_vehiculo',
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('nombre_plan',), name='unique_nombre_plan_activo'),
        ),
        migrations.DeleteModel(
            name='VehiculoPlan',
        ),
    ]
