# Generated by Django 4.2 on 2025-09-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0009_alter_items_nombre_items'),
        ('Requests', '0012_remove_vehiculoplan_id_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.categoriaformularios'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id_tipo_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requests.tipovehiculo'),
        ),
    ]
