# Generated by Django 4.2 on 2025-05-12 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Requests', '0002_plan_is_active_solicitud_is_active_and_more'),
        ('Result', '0002_opciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formulario', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_items', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id_categoria_opciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Result.categoriaopciones')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('id_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.formulario')),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requests.plan')),
            ],
        ),
        migrations.CreateModel(
            name='CreacionFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.formulario')),
                ('id_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.items')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formularioplan',
            constraint=models.UniqueConstraint(fields=('id_formulario', 'id_plan'), name='Formulario_plan_pk'),
        ),
        migrations.AddConstraint(
            model_name='creacionformulario',
            constraint=models.UniqueConstraint(fields=('id_formulario', 'id_items'), name='Creacion_formulario_pk'),
        ),
    ]
