# Generated by Django 4.2 on 2025-05-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_formulario_is_active_formularioplan_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFormularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='formulario',
            name='id_categoria',
            field=models.ManyToManyField(to='Forms.categoriaformularios'),
        ),
    ]
