# Generated by Django 4.2 on 2025-06-15 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0003_categoriaformularios_formulario_id_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='descripcion',
            new_name='tipo',
        ),
    ]
