# Generated by Django 4.2 on 2025-06-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0004_rename_descripcion_items_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='tipo',
            field=models.CharField(choices=[('STR', 'texto'), ('INT', 'numero entero'), ('DEC', 'numero decimal'), ('OPC', 'booleano'), ('FEC', 'fecha')], default='STR', max_length=250),
        ),
    ]
