# Generated by Django 4.2 on 2025-06-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0005_alter_items_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='tipo',
            field=models.CharField(choices=[('STR', 'texto'), ('INT', 'numero entero'), ('DEC', 'numero decimal'), ('OPC', 'booleano'), ('FEC', 'fecha')], default='OPC', max_length=250),
        ),
    ]
