# Generated by Django 4.2 on 2025-09-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0007_alter_items_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='tipo',
            field=models.CharField(choices=[('STR', 'texto'), ('INT', 'numero entero'), ('OPC', 'booleano'), ('FEC', 'fecha')], default='OPC', max_length=3),
        ),
    ]
