# Generated by Django 4.2 on 2025-09-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0008_alter_items_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='nombre_items',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=50),
        ),
    ]
