# Generated by Django 4.2 on 2025-03-29 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este nombre de usuario está en uso.'}, max_length=100, unique=True)),
                ('nit', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este nombre de usuario está en uso.'}, max_length=100, unique=True)),
                ('telefono', models.BigIntegerField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este nombre de usuario está en uso.'})),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este nombre de usuario está en uso.'}, max_length=100)),
                ('apellidos', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este nombre de usuario está en uso.'}, max_length=100)),
                ('cedula', models.BigIntegerField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este nombre de usuario está en uso.'}, unique=True)),
                ('correo', models.EmailField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este nombre de usuario está en uso.'}, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('AD', 'Administrador'), ('PR', 'Perito'), ('RC', 'Recepcionista'), ('CA', 'Administrador Convenio'), ('CC', 'Consultor Convenio')], max_length=2)),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_empleado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Access.empleado')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este nombre de usuario está en uso.'}, max_length=100)),
                ('ciudad', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este nombre de usuario está en uso.'}, max_length=100)),
                ('direccion', models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este nombre de usuario está en uso.'}, max_length=100)),
                ('telefono', models.BigIntegerField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este nombre de usuario está en uso.'})),
                ('estado', models.CharField(choices=[('AC', 'Activo'), ('IN', 'Inactivo')], default='AC', max_length=2)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Access.convenio')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Access.sucursal'),
        ),
    ]
