# Generated by Django 4.2 on 2025-05-11 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Access.empleado'),
        ),
    ]
