# Generated by Django 4.2 on 2025-05-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0002_convenio_is_active_alter_usuario_id_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
