# Generated by Django 4.2 on 2025-05-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0003_sucursal_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='convenio',
            new_name='id_convenio',
        ),
        migrations.AddField(
            model_name='empleado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
