# Generated by Django 4.2 on 2025-08-24 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0005_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 24, 23, 35, 44, 267163, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
