# Generated by Django 4.2 on 2025-08-28 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0006_alter_usersession_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
