# Generated by Django 4.2 on 2025-09-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0010_alter_usuario_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=15, unique=True),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('cedula',), name='unique_cedula_activo'),
        ),
    ]
